# Generated by Django 5.1.3 on 2025-01-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
