# Generated by Django 5.1.3 on 2025-01-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_post_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewpost1',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
