# Generated by Django 5.1.3 on 2025-01-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_viewpost1_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='tit',
        ),
    ]
