# Generated by Django 5.1.3 on 2025-01-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewpost1',
            name='like',
        ),
    ]
