# Generated by Django 5.1.3 on 2025-01-23 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_viewpost1_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tit',
            new_name='title',
        ),
    ]
