# Generated by Django 5.1.3 on 2025-01-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_tit_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
