# Generated by Django 5.1.3 on 2025-01-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
