# Generated by Django 5.1.3 on 2025-01-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_viewpost1_liked_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewpost1',
            name='liked',
        ),
    ]
