# Generated by Django 5.1.3 on 2025-01-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
