# Generated by Django 5.1.3 on 2025-01-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_viewpost1_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewpost1',
            name='avatar',
        ),
    ]
