# Generated by Django 5.1.3 on 2025-01-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_like_unique_together_remove_post_liked_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
