# Generated by Django 5.1.3 on 2025-01-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
